### ISSUE TITLE
Not Working 

### ISSUE THREAD

**Issue by infopriyank** [Exygy/wp-pattern-library#1]
Hi Admin,

I am just install this plugin in latest WP and check inside back end and there is no entry inside admin.
please give me solution and also how to use this plugin? how to make pattern.

Regards
Priyank

**Comment by creativecoder** [comment]
Priyank,

This is a developer only plugin. There are no options in the WordPress admin. Please see the readme for how to get started: https://github.com/Exygy/wp-pattern-library#create-a-pattern-library
