### ISSUE TITLE
Gulp bugs out.

### ISSUE THREAD

**Issue by brightonmike** [Exygy/wp-pattern-library#2]
Hello! This looks potentially like an awesome idea and very helpful for my projects. However, I can't get it working.

First of all - it didn't pick up patterns in my folder straight away. Somehow, without me really doing anything, it suddenly started working. Not sure there.

However patterns don't render correctly when using YML and I can't include them. I suspect this is because I wasn't running `npm install` and `gulp` - so that's what I'm trying. But this bugs out, I get the following:

```
Entry module not found: Error: Cannot resolve module 'babel' in /Users/user/Local Sites/test-site/app/public/wp-content/plugins/wp-pattern-library-master
resolve module babel in /Users/user/Local Sites/test-site/app/public/wp-content/plugins/wp-pattern-library-master
  looking for modules in /Users/user/Local Sites/test-site/app/public/wp-content/plugins/wp-pattern-library-master/node_modules
    module variation babel-webpack-loader
      /Users/user/Local Sites/test-site/app/public/wp-content/plugins/wp-pattern-library-master/node_modules/babel-webpack-loader doesn't exist (module as directory)
      resolve 'file' babel-webpack-loader in /Users/user/Local Sites/test-site/app/public/wp-content/plugins/wp-pattern-library-master/node_modules
        resolve file
          /Users/user/Local Sites/test-site/app/public/wp-content/plugins/wp-pattern-library-master/node_modules/babel-webpack-loader doesn't exist
          /Users/user/Local Sites/test-site/app/public/wp-content/plugins/wp-pattern-library-master/node_modules/babel-webpack-loader.webpack-loader.js doesn't exist
          /Users/user/Local Sites/test-site/app/public/wp-content/plugins/wp-pattern-library-master/node_modules/babel-webpack-loader.web-loader.js doesn't exist
          /Users/user/Local Sites/test-site/app/public/wp-content/plugins/wp-pattern-library-master/node_modules/babel-webpack-loader.loader.js doesn't exist
          /Users/user/Local Sites/test-site/app/public/wp-content/plugins/wp-pattern-library-master/node_modules/babel-webpack-loader.js doesn't exist
```

**Comment by creativecoder** [comment]
npm packages and gulp are only needed for plugin development, not for usage.

Do you mean yml frontmatter in your patterns for setting default template variables isn't working? What exactly happens when you use it?

**Comment by brightonmike** [comment]
The error I get when trying to include them is:

`) Warning: file_get_contents(/app/public/wp-content/themes/bullets_starter_theme/pattern-library/materials/atoms/button.php): failed to open stream: No such file or directory in /app/public/wp-content/plugins/wp-pattern-library-master/includes/global.php on line 72`

I'm using this:

`get_pattern( 'atom', 'button', ['text' => 'Submit'] );`

And in my theme I have:

pattern-library/materials/atoms/button.html

I'm not sure why it's looking for a .php file. I did try using .php but then it spits out the whole file including the YML.

**Comment by brightonmike** [comment]
BTW - Pattern Library itself compiles - although the YML doesn't work there either. Spits out as plain text.

**Comment by creativecoder** [comment]
Pattern library partials must be `.php` files. YML is currently only supported as frontmatter in those files. You need to make sure the YML is at the top of the partial file and is encapsulated by `---` dividers, on their own lines, above and below the YML. See the button example in the README.

**Comment by brightonmike** [comment]
Got it working. I had a rogue space before the `---` that was causing it to bug out.

Damnit, my bad, but great that it works. Cheers.
